name: Sync to GitLab

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Push to GitLab
        run: |
          git config --global user.name 'fayezzouari'
          git config --global user.email 'fayez.zouari@insat.ucar.tn'
          git remote add gitlab https://fayezzouari:${{ secrets.GITLAB_TOKEN }}@gitlab.com/fayezzouari/BeagleMind-RAG-PoC
          git push gitlab main --force
