name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # or specify a version like '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black flake8  # or pylint if you prefer

      - name: Run Black
        run: |
          black --check .

      - name: Run flake8
        run: |
          flake8 .

  sync:
    needs: lint  # Only run sync if lint passes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Full clone
          
      - name: Push to GitLab
        run: |
          git config --global user.name 'fayezzouari'
          git config --global user.email 'fayez.zouari@insat.ucar.tn'
          git remote add gitlab https://fayezzouari:${{ secrets.GITLAB_TOKEN }}@gitlab.com/fayezzouari/BeagleMind-RAG-PoC
          git push gitlab main --force
